Feature/proposal
zhao1995chen/wowcho-mgmt-api pull request #77
Opened 2023-04-28 15:45 UTC by rider159159

2023-05-02 16:35 UTC, zhao1995chen commented
測試無輸入 id 直接打 更新 API，回傳錯誤訊息不應該為「專案網址已使用」

<img width="647" alt="image" src="https://user-images.githubusercontent.com/53460349/235728611-3b3998b1-8996-4ebd-a370-9d5b4482ac10.png">

2023-05-02 16:38 UTC, zhao1995chen commented
未輸入 id 打 刪除 API，不應回傳成功訊息

<img width="647" alt="image" src="https://user-images.githubusercontent.com/53460349/235729315-af81716f-7698-4140-be64-c209bf216a0c.png">

2023-05-02 16:50 UTC, zhao1995chen commented
當 `ageLimit` 為 `null` 打 新增 API，`ageLimit` 錯誤提示訊息依舊存在，interface 定義 `ageLimit` 型態包含 `Null`，理應不能報錯

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235731893-5d9a8e1a-26ba-4d28-acaa-f2e1aa62dafd.png">

2023-05-02 17:03 UTC, zhao1995chen commented
當 `category` 為 `-10` 打 新增 API，出現使用者看不懂的錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235734646-b03a9a79-0e32-442f-a4eb-0f6d1eb2bde5.png">

2023-05-02 17:06 UTC, zhao1995chen commented
當 `description` 為空字串 打 新增 API，出現錯誤訊息 `募資活動詳細介紹必填`，應回`不能為空`

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235735225-565418f9-42b9-49a6-a7e2-657815afa4e9.png">

當 `description` 為 `"     " ` 打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235735456-d511adfe-d216-4126-a3eb-83c086690781.png">

2023-05-02 17:07 UTC, zhao1995chen commented
當 `name` 為數字型態打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235735859-abbd1db1-b46b-4355-a35a-32972f811bee.png">

2023-05-02 17:10 UTC, zhao1995chen commented
當 `imageUrl` 為非網址格式字串打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235736090-53f5f75a-cf0a-4859-9fd7-fc8fda35430e.png">

當 `imageUrl` 為數字型態打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235736289-a910b097-999d-482d-a8b9-e74b4f57e8b6.png">

2023-05-02 17:14 UTC, zhao1995chen commented
當 `summary` 為空字串 打 新增 API，出現錯誤訊息 `募資活動詳細介紹必填`，應回 `不能為空`

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235737050-e61887ee-c073-4eab-bad7-32d8bba64ae3.png">

當 `summary` 為 "     "  打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235736894-415787fc-b08e-419e-a697-2b775e86bcc4.png">

當`summary` 為數字型態打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235736801-4777557e-c3af-48ac-af5b-35901a05465e.png">

2023-05-02 17:18 UTC, zhao1995chen commented
當 `targetPrice` 為 `-1` 打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235737340-b7bd638f-c1d9-489c-ac17-e08403d15146.png">

當 `targetPrice` 為字串型態打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235737556-bf457277-35da-4afa-b9c1-c7e5164d4211.png">

當 `targetPrice` 為 `"e^1"` 打 新增 API，回傳使用者看不懂的錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235737734-c5e219ef-4be9-4ca5-96e9-ede7ba1bb203.png">

2023-05-02 17:25 UTC, zhao1995chen commented
當 `endTime` 為 `0` 打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235738234-5d05b1bb-f544-409a-b170-eee103905211.png">

當 `endTime` 為 `-1` 打 新增 API，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235738584-9eae22f0-b5c6-46ff-be38-3fc703f7c14c.png">

當 `endTime` 為 `20` 打 新增 API，小於當下時間，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235738808-406d0e7e-596c-48a9-b0af-9f4922f686ac.png">

當 `endTime` 為字串型態打 新增 API，錯誤訊息不應該是 `募資活動結束時間必填`

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235738197-0c257425-ff37-486d-ad6c-025ac614ab11.png">

上述問題 `startTime` 應也會出現，不詳列

當 `endTime` 小於 `startTime` 打 新增 API，結束時間小於起始時間，沒有錯誤訊息

<img width="973" alt="image" src="https://user-images.githubusercontent.com/53460349/235739248-9545fd51-4a1e-4699-9238-ce64df6572c6.png">

2023-05-02 17:28 UTC, zhao1995chen requested changes
針對變數命名先行 review，後續邏輯問題若有問題再補上

2023-05-03 08:26 UTC, zhao1995chen commented
當 `body` 為空 打 修改 API，回傳錯誤訊息不應該是 `專案網址已使用`

![image](https://user-images.githubusercontent.com/53460349/235864929-21c69912-8841-4da4-a97d-30a076ffa2f3.png)

直接使用回傳資料打 修改 API，不應回傳錯誤訊息

![image](https://user-images.githubusercontent.com/53460349/235865275-b20b19c4-85fc-444c-97cf-f777b3eb61af.png)

註解 `customizedUrl` 打 修改 API，不應回傳錯誤訊息

![image](https://user-images.githubusercontent.com/53460349/235865746-4f4acedd-5814-4d80-87c1-5e9916d5aa9e.png)

打 修改 API，不應回傳錯誤訊息 `募資活動 ID 錯誤`

![image](https://user-images.githubusercontent.com/53460349/235865985-18bfe879-89f3-403b-a917-bf3c653d23b2.png)

> 修改 API 後續功能無法被測試

2023-05-03 08:40 UTC, zhao1995chen commented
當 body 為空 打 刪除 API，應該回傳錯誤訊息

![image](https://user-images.githubusercontent.com/53460349/235867637-336bb867-f41e-4e6b-ac6c-b221ab553337.png)

打刪除 API，回傳了使用者看不懂的錯誤訊息

![image](https://user-images.githubusercontent.com/53460349/235868160-a95332ee-4285-469a-bbcb-9ad31a6e02ae.png)

使用無效 `id` 打 刪除 API，應該回傳錯誤訊息

![image](https://user-images.githubusercontent.com/53460349/235868958-a24b3107-e693-459c-b686-46432a6194c6.png)

2023-05-03 08:43 UTC, zhao1995chen requested changes
@rider159159 Code review finished. Please check and fix bugs.

2023-05-03 08:43 UTC, zhao1995chen commented on controllers/Proposal.controller.ts
> +      console.log(array)
console 不能進 dev 及 production

2023-05-03 08:43 UTC, zhao1995chen commented on models/Proposal.model.ts
錯誤訊息需使用 errorHandler.ts function

2023-05-03 08:43 UTC, zhao1995chen commented on controllers/Proposal.controller.ts
錯誤訊息需使用 errorHandler.ts function

2023-05-07 11:11 UTC, zhao1995chen commented
### 新增 API

當 `image` 為 `123` 打 新增 API，`image` 沒有錯誤訊息
<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236671365-78704cfc-3a76-4d6b-b977-5cbb7f9c7606.png">

當 `image` 為數字型態打 新增 API，沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236671440-e3266489-81e3-4f8c-9189-361f38da245b.png">

當 `video` 為 `1232` 打 新增 API，`video` 沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236671741-d95a1ecb-d6bd-4e84-ae57-a3d4a49bf7ce.png">

當 `video` 為數字型態打 新增 API，沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236671782-f63e5894-2f35-452e-84c9-e0d9f0c7daba.png">

當 `targetPrice` 為 `"e^1" `打 新增 API，回傳使用者看不懂的錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672166-7d97fa31-2569-48c3-82aa-c8ad44800b82.png">

當 `ageLimit` 為 `-0` 打 新增 API，`ageLimit` 沒有錯誤提示訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236660036-c88c8f4c-859d-4b50-b595-3ad5d06a9133.png">

當 `startTime` 為 `0` 打 新增 API，出現錯誤訊息 `僅能輸入零以上的數字`，應回 `僅能超過當前時間`

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672631-6e7806e2-81ed-4223-9928-8f85b8597e02.png">

當 `startTime` 為 `-1` 打 新增 API，出現錯誤訊息 `僅能輸入零以上的數字`，應回 `僅能超過當前時間`

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672698-e958f3c6-4655-4d2d-8f4c-3a5fbf2f8189.png">

當 `startTime` 為 `200` 打 新增 API，小於當下時間，沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236659827-5284f39f-b98a-4624-96f8-fbfe703a63cf.png">

當 `startTime` 為字串型態 打 新增 API，沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672724-bf8949ab-6284-4e04-a0b6-bb4ad1274dbb.png">

當 `endTime` 為字串型態打 新增 API，出現錯誤訊息 `僅能超過當前時間`，應回 `型態錯誤`

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672335-8c44161c-3b7c-463c-9d00-d36d3ec36f35.png">

當 `endTime` 小於 `startTime` 打 新增 API，結束時間小於起始時間，沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672500-91588ea4-149a-43ee-9c03-4722852acd2d.png">

當 `customizedUrl` 為數字型態 打 新增 API，沒有錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672823-4dea3fe6-5069-4032-94ec-712758c0f439.png">

當 `customizedUrl` 使用未被使用過的值 打 新增 API，不應回傳錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236672908-3ea10c82-ff50-4408-95ca-127626a4ac03.png">

承諾與告示為空值 打 新增 API，應在初始化時被建立，並且關聯回傳

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673077-df355a37-7f72-44cf-a2a0-710791576101.png">

承諾與告示有值 打 新增 API，~`promiseId`~ `promisesId` 不應該為空值

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673165-8a625fd4-2645-40fb-a33d-fc8354be69c6.png">

### 修改 API

直接使用回傳資料，出現錯誤訊息 `請確認你的資料是否正確`，應不能報錯

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673710-4aa00a81-7e8c-4165-8d18-6cc9adad8511.png">

直接使用另個專案的 data，出現錯誤訊息 `請確認你的資料是否正確`，應不能報錯

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673495-36e0e369-0482-4254-a01e-29e53e17840a.png">

註解 `customizedUrl`，不應回傳錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673516-93a14a66-06f0-4e98-becb-4fb1ed0c973f.png">

修改資料出現錯誤訊息 `請確認你的資料是否正確`，應不能報錯

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673765-bbe9df7f-24bc-4272-abbf-ad52867ca327.png">

### 刪除 API

使用無效 id 打 刪除 API，應該回傳錯誤訊息

<img width="971" alt="image" src="https://user-images.githubusercontent.com/53460349/236673987-9e214ac8-43f2-47dd-b7cd-80019b5ebb26.png">

2023-05-07 14:58 UTC, rider159159 commented
# 以調整的
>當 image 為 123 打 新增 API，image 沒有錯誤訊息

> 當 image 為數字型態打 新增 API，沒有錯誤訊息

> 當 startTime 為 0 打 新增 API，出現錯誤訊息 僅能輸入零以上的數字，應回 僅能超過當前時間

> 當 startTime 為 -1 打 新增 API，出現錯誤訊息 僅能輸入零以上的數字，應回 僅能超過當前時間

> 當 startTime 為 200 打 新增 API，小於當下時間，沒有錯誤訊息


# 有問題的
## 新增 API
> 當 video 為 1232 打 新增 API，video 沒有錯誤訊息

> 當 video 為數字型態打 新增 API，沒有錯誤訊息

> 當 startTime 為字串型態 打 新增 API，沒有錯誤訊息

> 當 endTime 為字串型態打 新增 API，出現錯誤訊息 僅能超過當前時間，應回 型態錯誤

>當 customizedUrl 為數字型態 打 新增 API，沒有錯誤訊息

-  #78 中有回報，字串轉數字，數字轉字串問題暫不處理
https://github.com/zhao1995chen/wowcho-mgmt-api/issues/78

> 當 targetPrice 為 "e^1" 打 新增 API，回傳使用者看不懂的錯誤訊息
- 這個回報是 schema 認證 該欄位型別不是 number，字串轉數字行問題，如上所述暫不處理

> 當 ageLimit 為 -0 打 新增 API，ageLimit 沒有錯誤提示訊息
- JS 本身語法限制問題， `-0 === 0` 回傳  true ，由於前端僅會使用 0、1 兩個下拉選單，因此不做處理
![image](https://user-images.githubusercontent.com/49020558/236683822-90f1988d-d78a-4168-ad50-dce64a45ec4d.png)

> 當 endTime 小於 startTime 打 新增 API，結束時間小於起始時間，沒有錯誤訊息
- 確認沒問題
![image](https://user-images.githubusercontent.com/49020558/236684276-9693985b-6f8c-4b13-90cf-03a16dbfd257.png)

> 當 customizedUrl 使用未被使用過的值 打 新增 API，不應回傳錯誤訊息
- 確認沒問題，圖中範例是 "123" 有可能之前已使用


## 修改 API
> 直接使用回傳資料，出現錯誤訊息 請確認你的資料是否正確，應不能報錯
- 根據 API 規格，使用的是 `id` 做認證，直接使用回傳的是 `_id` ，需再確認是由前端統一處理，還是後端修改欄位。

>註解 customizedUrl，不應回傳錯誤訊息
-註解 customizedUrl 後，能夠正常回應
![image](https://user-images.githubusercontent.com/49020558/236682468-da1cf794-6cd5-42e0-aba8-1966ec2025ab.png)

>修改資料出現錯誤訊息 請確認你的資料是否正確，應不能報錯
- 測試正確，欄位盡量按照你提供照片調整

![image](https://user-images.githubusercontent.com/49020558/236682887-f6e426dc-06ba-4ab2-b1c1-5bf1f92c97c4.png)


## 刪除 API

> 使用無效 id 打 刪除 API，應該回傳錯誤訊息
- 測試會回報

![image](https://user-images.githubusercontent.com/49020558/236681641-e5fe7a10-530b-4b25-8ee8-cfae1971b6ee.png)

2023-05-07 15:24 UTC, rider159159 commented
改由 bugfix 分支，請 @zhao1995chen 檢視 ， https://github.com/zhao1995chen/wowcho-mgmt-api/pull/81

2023-05-12 08:28 UTC, rider159159 commented
新增三個字串欄位，不做驗證預設空字串，以取代 `promiseId ` 承諾告示 欄位
- serviceContact: string;  // 客服聯絡方式
- risksChallenge: string; 	// 風險與挑戰
- returnGoods: string;	// 退換貨方式

`customizedUrl` 調整成僅能接受字串，新增、編輯，若輸入空字串以 uuid 取代

2023-05-18 16:48 UTC, zhao1995chen approved these changes

2023-05-18 16:50 UTC, zhao1995chen commented
先 pass 以推進後續開發速度，有問題再開單處理

2023-05-18 16:51 UTC, merged